/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Helper;
import Controlador.HelperMCD;
import Controlador.HelperMCS;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis
 */
public class App_PreLiqCaja extends javax.swing.JInternalFrame {

    /**
     * Creates new form App_PreLiqCaja
     */
    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel mod = new DefaultTableModel();
    HelperMCD oMCD;
    HelperMCS oMCS;
    Helper oper;   
   
    public void updateT() {
        oper.limpiaTabla(modelo, tablals);
        modelo = oMCS.getMcsByUser(modelo, Integer.parseInt(App_Principal.codigo.getText()),0,1);
        tablals.setModel(modelo);
    }
    public void updateTD() {
        oper.limpiaTabla(mod, tablald);
        mod = oMCD.getMcdByUser(mod, Integer.parseInt(App_Principal.codigo.getText()),0);
        tablald.setModel(mod);
    }
    
        private Timer timer;
    /*
     * 1000ms ---- 1s
     *  120.000ms = 2m
     * */
    private int delay = 60000;
    
    
    public void correr(){
        
        SwingUtilities.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                ActionListener action = new ActionListener()
                {   
                    @Override
                    public void actionPerformed(ActionEvent event)
                    {
                        updateT();
                        updateTD();
                    }
                };
 
                timer = new Timer(delay, action);
                timer.setInitialDelay(0);
                timer.start();
            }
        });
    }
    
    
    public App_PreLiqCaja() {
        initComponents();
        String Titulos[]={"ID","SERIE","FECHA","DESCRIPCIÓN","IMPORTE","LIQUIDADO","ESTADO"};
        modelo.setColumnIdentifiers(Titulos);
        mod.setColumnIdentifiers(Titulos);
        oper = new Helper();
        oMCD = new HelperMCD();
        oMCS = new HelperMCS();
        modelo = oMCS.getMcsByUser(modelo, Integer.parseInt(App_Principal.codigo.getText()),0,1);
        mod = oMCD.getMcdByUser(mod, Integer.parseInt(App_Principal.codigo.getText()),0);
        tablals.setModel(modelo);
        tablald.setModel(mod);
        tablals.getColumnModel().getColumn(0).setPreferredWidth(1);// 
        tablals.getColumnModel().getColumn(1).setPreferredWidth(125);
        tablals.getColumnModel().getColumn(2).setPreferredWidth(75);
        tablals.getColumnModel().getColumn(3).setPreferredWidth(200);
        tablals.getColumnModel().getColumn(4).setPreferredWidth(50);
        tablals.getColumnModel().getColumn(5).setPreferredWidth(50);
        tablals.getColumnModel().getColumn(6).setPreferredWidth(50);
        tablald.getColumnModel().getColumn(0).setPreferredWidth(1);// 
        tablald.getColumnModel().getColumn(1).setPreferredWidth(125);
        tablald.getColumnModel().getColumn(2).setPreferredWidth(75);
        tablald.getColumnModel().getColumn(3).setPreferredWidth(200);
        tablald.getColumnModel().getColumn(4).setPreferredWidth(50);
        tablald.getColumnModel().getColumn(5).setPreferredWidth(50);
        tablald.getColumnModel().getColumn(6).setPreferredWidth(50);
        this.correr();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablald = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablals = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jButton3.setText("SALIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("ABRIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LIQUIDACIONES PENDIENTES EN DOLARES:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 1, 12))); // NOI18N

        tablald.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        tablald.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaldMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablald);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LIQUIDACIONES PENDIENTES EN SOLES:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft Sans Serif", 1, 12))); // NOI18N

        tablals.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        tablals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablalsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablals);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(tablals.getSelectedRow()==-1 && tablald.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"DEBE SELECCIONAR UNA LIQUIDACIÓN PENDIENTE");
        } else if (tablals.getSelectedRow() >= 0) {
            int fila = tablals.getSelectedRow();
            App_LiquidarCC.codLiq = Integer.parseInt(tablals.getValueAt(fila, 0).toString());
            App_LiquidarCC.bandera = 1;
            App_LiquidarCC eP = new App_LiquidarCC();
            App_Principal.escritorio.add(eP);
            eP.setLocation(100, 100);
            eP.show();
        } else {
            int fila = tablald.getSelectedRow();
            App_LiquidarCC.codLiq = Integer.parseInt(tablald.getValueAt(fila, 0).toString());
            App_LiquidarCC.bandera = 2;
            App_LiquidarCC eP = new App_LiquidarCC();
            App_Principal.escritorio.add(eP);
            eP.setLocation(100, 100);
            eP.show();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tablals.setEnabled(true);
        tablald.setEnabled(true);
        jPanel1.setEnabled(true);
        jPanel2.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablalsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablalsMouseClicked
        // TODO add your handling code here:
        jPanel1.setEnabled(false);
        tablald.setEnabled(false);
        tablald.clearSelection();
    }//GEN-LAST:event_tablalsMouseClicked

    private void tablaldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaldMouseClicked
        // TODO add your handling code here:
        jPanel2.setEnabled(false);
        tablals.setEnabled(false);
        tablals.clearSelection();
        
    }//GEN-LAST:event_tablaldMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tablald;
    public static javax.swing.JTable tablals;
    // End of variables declaration//GEN-END:variables
}
