/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Helper;
import Controlador.HelperDMCD;
import Controlador.HelperDMCS;
import Controlador.HelperMCD;
import Controlador.HelperMCS;
import Modelo.DetalleMcd;
import Modelo.DetalleMcs;
import Modelo.MovimientosCajas;
import Modelo.MovimientosCajasd;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis
 */
public class App_DLiqCC extends javax.swing.JInternalFrame {

    /**
     * Creates new form App_DLiqCC
     */
    HelperDMCS oDMCS;
    HelperDMCD oDMCD;
    HelperMCS oMCS;
    HelperMCD oMCD;
    Helper oper;
    
    
    public static int codDetLiq;
    
    public void updateT(long id,int valor) {
        if (valor == 1) {
            DefaultTableModel mod = (DefaultTableModel) App_LiquidarCC.tablalcc.getModel();
            oper.limpiaTabla(mod, App_LiquidarCC.tablalcc);
            mod = oDMCS.obtenerDMCS((DefaultTableModel) App_LiquidarCC.tablalcc.getModel(), 0, id);
            App_LiquidarCC.tablalcc.setModel(mod);
        } else {
            DefaultTableModel mod = (DefaultTableModel) App_LiquidarCC.tablalcc.getModel();
            oper.limpiaTabla(mod, App_LiquidarCC.tablalcc);
            mod = oDMCD.obtenerDMCD((DefaultTableModel) App_LiquidarCC.tablalcc.getModel(), 0, id);
            App_LiquidarCC.tablalcc.setModel(mod);
        }

    }
    
    public void updateTSD(int valor) {
        if(valor == 1){
            DefaultTableModel mod = (DefaultTableModel) App_PreLiqCaja.tablals.getModel();
            oper.limpiaTabla(mod, App_PreLiqCaja.tablals);
            mod = oMCS.getMcsByUser(mod, Integer.parseInt(App_Principal.codigo.getText()),0,1);
            App_PreLiqCaja.tablals.setModel(mod);
        }else{
            DefaultTableModel mod = (DefaultTableModel) App_PreLiqCaja.tablald.getModel();
            oper.limpiaTabla(mod, App_PreLiqCaja.tablald);
            mod = oMCD.getMcdByUser(mod, Integer.parseInt(App_Principal.codigo.getText()),0);
            App_PreLiqCaja.tablald.setModel(mod);  
        }

    }


    public App_DLiqCC() {
        initComponents();
        oper = new Helper();
        oDMCS = new HelperDMCS();
        oDMCD = new HelperDMCD();
        oMCS = new HelperMCS();
        oMCD = new HelperMCD();
        if(App_LiquidarCC.bandera==1){
            DetalleMcs detm = oDMCS.buscaDMCS(codDetLiq);
            cod.setText(String.valueOf(detm.getDmcsId()));
            umet.setText(detm.getUnidadmId());
            sub.setText(String.valueOf(detm.getDmcsSt()));
            desc.setText(detm.getDmcsDesc());
            cant.setText(String.valueOf(detm.getDmcsCant()));
            importe.setText(String.valueOf(detm.getDmcsImporte()));
        }else{
            DetalleMcd detm = oDMCD.buscaDMCD(codDetLiq);
            cod.setText(String.valueOf(detm.getDmcdId()));
            umet.setText(detm.getUnidadmId());
            sub.setText(String.valueOf(detm.getDmcdSt()));
            desc.setText(detm.getDmcdDesc());
            cant.setText(String.valueOf(detm.getDmcdCant()));
            importe.setText(String.valueOf(detm.getDmcdImporte()));
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        umet = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        desc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cant = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        importe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sub = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboTD = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        serie = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        prov = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        totald = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fechar = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("ID:");

        cod.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        cod.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("UNIDAD DE MEDIDA:");

        umet.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("DESCRIPCIÓN:");

        desc.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("CANT:");

        cant.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        cant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantKeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("IMPORTE:");

        importe.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        importe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                importeKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("SUB-TOTAL:");

        sub.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        sub.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("TIPO DOC:");

        cboTD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<>", "FACTURA", "BOLETA", "SIN DOCUMENTO" }));

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("SERIE:");

        serie.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("PROVEEDOR:");

        prov.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("TOTAL DOC:");

        totald.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("DOC FECHA:");

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("GUARDAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(prov, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(369, 369, 369)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(totald, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cod, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(umet))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sub))
                            .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cboTD, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(cant, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(importe)
                                    .addComponent(serie))))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cod)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(umet))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cant)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(importe))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serie))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prov))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totald)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fechar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cantKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantKeyReleased
        // TODO add your handling code here:
        if("".equals(cant.getText()) || "".equals(importe.getText())){
            
        }else{
        Double c = Double.parseDouble(cant.getText());
        Double x = Double.parseDouble(importe.getText());
        
        sub.setText(String.valueOf(c*x));
        }
    }//GEN-LAST:event_cantKeyReleased

    private void importeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_importeKeyReleased
        // TODO add your handling code here:
        if ("".equals(cant.getText()) || "".equals(importe.getText())) {

        } else {
            Double c = Double.parseDouble(cant.getText());
            Double x = Double.parseDouble(importe.getText());

            sub.setText(String.valueOf(c * x));
        }
    }//GEN-LAST:event_importeKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(App_LiquidarCC.bandera==1){
            DetalleMcs detm = oDMCS.buscaDMCS(codDetLiq);
            oDMCS.aDMCS(detm.getDmcsId(), umet.getText(), desc.getText(),Double.parseDouble(cant.getText()),
            Double.parseDouble(importe.getText()), Double.parseDouble(sub.getText()), 
            cboTD.getSelectedItem().toString(), prov.getText(), serie.getText(), fechar.getDate(), Double.parseDouble(totald.getText()));
            MovimientosCajas tempmcs = oMCS.buscaMCS(detm.getMovimientosCajas().getMcsId());
            oMCS.aILiquidado(detm.getMovimientosCajas().getMcsId(), tempmcs.getMcsImportel()+Double.parseDouble(sub.getText()));
            updateT(detm.getMovimientosCajas().getMcsId(),1);
            int pl = oDMCS.searchLiqS(detm.getMovimientosCajas().getMcsId(),0);
            if(pl > 0){
                this.dispose();
            }else{
                //actualizar estado MCS a SUBIDO
                oMCS.aEstado(detm.getMovimientosCajas().getMcsId(), 1);
                App_LiquidarCC.btnS.doClick();
                updateTSD(1);
                this.dispose();
            }
            
            
        }else{
            DetalleMcd detmd = oDMCD.buscaDMCD(codDetLiq);
            
            oDMCD.aDMCD(detmd.getDmcdId(), umet.getText(), desc.getText(), Double.parseDouble(cant.getText()),
            Double.parseDouble(importe.getText()), Double.parseDouble(sub.getText()),
            cboTD.getSelectedItem().toString(), prov.getText(), serie.getText(), fechar.getDate(), Double.parseDouble(totald.getText()));
            MovimientosCajasd tempmcd = oMCD.buscaMCD(detmd.getMovimientosCajasd().getMcdId());
            oMCD.aILiquidado(detmd.getMovimientosCajasd().getMcdId(), tempmcd.getMcdImportel()+Double.parseDouble(sub.getText()));
            updateT(detmd.getMovimientosCajasd().getMcdId(),2);
            
            int pl = oDMCD.searchLiqD(detmd.getMovimientosCajasd().getMcdId(),0);
            if(pl > 0){ 
                this.dispose();
            }else{
                //actualizar estado MCD a SUBIDO
                oMCD.aEstado(detmd.getMovimientosCajasd().getMcdId(), 1);
                App_LiquidarCC.btnS.doClick();
                updateTSD(2);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cant;
    private javax.swing.JComboBox<String> cboTD;
    private javax.swing.JTextField cod;
    private javax.swing.JTextField desc;
    private com.toedter.calendar.JDateChooser fechar;
    private javax.swing.JTextField importe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField prov;
    private javax.swing.JTextField serie;
    private javax.swing.JTextField sub;
    private javax.swing.JTextField totald;
    private javax.swing.JTextField umet;
    // End of variables declaration//GEN-END:variables
}
