/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Helper;
import Controlador.HelperDMCD;
import Controlador.HelperDMCS;
import Controlador.HelperMCD;
import Controlador.HelperMCS;
import Modelo.DetalleMcd;
import Modelo.DetalleMcs;
import Modelo.MovimientosCajas;
import Modelo.MovimientosCajasd;
import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis
 */
public class App_LiquidarCC extends javax.swing.JInternalFrame {

    /**
     * Creates new form App_LiquidarCC
     */
    DefaultTableModel modelo = new DefaultTableModel();
    public static int bandera;
    public static long codLiq;
    HelperMCS oMCS;
    HelperMCD oMCD;
    HelperDMCS oDMCS;
    HelperDMCD oDMCD;
    Helper oper;
    
    
    public App_LiquidarCC() {
        initComponents();
        oMCS = new HelperMCS();
        oMCD = new HelperMCD();
        oDMCS = new HelperDMCS();
        oDMCD = new HelperDMCD();
        oper = new Helper();
        
        String t[] = {"COD", "DESCRIPCIÓN", "U.MED", "CANT.","P.U", "Importe","ESTADO"};
        modelo.setColumnIdentifiers(t);
        tablalcc.setModel(modelo);
        tablalcc.getColumnModel().getColumn(0).setPreferredWidth(1);// 
        tablalcc.getColumnModel().getColumn(1).setPreferredWidth(250);
        tablalcc.getColumnModel().getColumn(2).setPreferredWidth(25);
        tablalcc.getColumnModel().getColumn(3).setPreferredWidth(25);
        tablalcc.getColumnModel().getColumn(4).setPreferredWidth(50);
        tablalcc.getColumnModel().getColumn(5).setPreferredWidth(75);
        tablalcc.getColumnModel().getColumn(6).setPreferredWidth(75);

        String tix = tit.getText();
        String imp = il.getText();
        if(bandera==1){
            tit.setText(tix+" PEN");
            il.setText(imp + " (S/.):");
            MovimientosCajas lmcs = oMCS.buscaMCS(codLiq);
            serie.setText(lmcs.getMcsSerie());
            desc.setText(lmcs.getMcsDesc());
            fecha.setText(lmcs.getMcsFecha().toString());
            liq.setText(lmcs.getMcsImporte().toString());
            
            /*DETALLE DE LIQUIDACION */
            
            List<DetalleMcs> listaa = oDMCS.obtenerDMCS(codLiq,0);
            Iterator<DetalleMcs> iter = listaa.iterator();

            while (iter.hasNext()) {
                DetalleMcs p = (DetalleMcs) iter.next();
                modelo.addRow(new Object[]{p.getDmcsId(),p.getDmcsDesc(),p.getUnidadmId(),p.getDmcsCant(),p.getDmcsImporte(),p.getDmcsSt(),oper.validarEstado(p.getDmcsEstado())});
            }
            tablalcc.setModel(modelo);
            
        }else{
            tit.setText(tix+" USD");
            il.setText(imp + " ($):");
            MovimientosCajasd lmcd = oMCD.buscaMCD(codLiq);
            serie.setText(lmcd.getMcdSerie());
            desc.setText(lmcd.getMcdDesc());
            fecha.setText(lmcd.getMcdFecha().toString());
            liq.setText(lmcd.getMcdImporte().toString());
                        /*DETALLE DE LIQUIDACION */
            
            List<DetalleMcd> listaa = oDMCD.obtenerDMCD(codLiq);
            Iterator<DetalleMcd> iter = listaa.iterator();

            while (iter.hasNext()) {
                DetalleMcd p = (DetalleMcd) iter.next();
                modelo.addRow(new Object[]{p.getDmcdId(),p.getDmcdDesc(),p.getUnidadmId(),p.getDmcdCant(),p.getDmcdImporte(),p.getDmcdSt(),oper.validarEstado(p.getDmcdEstado())});
            }
            tablalcc.setModel(modelo);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        il = new javax.swing.JLabel();
        serie = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        liq = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablalcc = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        btnS = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        tit.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        tit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tit.setText("LIQUIDACIÓN DE CAJA CHICA");

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("SERIE:");

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("FECHA:");

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("DESCRIPCIÓN:");

        il.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        il.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        il.setText("IMPORTE A LIQUIDAR");

        serie.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        serie.setText("XXXXX");

        desc.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        desc.setText("XXXXX");

        liq.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        liq.setText("XXXXX");

        fecha.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        fecha.setText("XXXXX");

        tablalcc.setToolTipText("");
        jScrollPane1.setViewportView(tablalcc);

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DETALLE DE LIQUIDACIÓN");

        btnS.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        btnS.setText("SALIR");
        btnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16)); // NOI18N
        jButton2.setText("LIQUIDAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(serie, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                    .addComponent(desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(il, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(liq, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnS, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(serie))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(desc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(il)
                    .addComponent(liq)
                    .addComponent(fecha))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        App_DLiqCC.codDetLiq = Integer.parseInt(tablalcc.getValueAt(tablalcc.getSelectedRow(), 0).toString());
        App_DLiqCC eP = new App_DLiqCC();
        App_Principal.escritorio.add(eP);
        eP.setLocation(350, 100);
        eP.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnS;
    private javax.swing.JLabel desc;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel il;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel liq;
    private javax.swing.JLabel serie;
    public static javax.swing.JTable tablalcc;
    private javax.swing.JLabel tit;
    // End of variables declaration//GEN-END:variables
}
