/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Helper;
import Controlador.HelperConductor;
import Controlador.HelperRemolque;
import Controlador.HelperST;
import Controlador.HelperSV;
import Controlador.HelperTractos;
import Controlador.HelperUnidadM;
import Controlador.HelperUsuarios;
import Modelo.Choferes;
import Modelo.DetalleSv;
import Modelo.Remolques;
import Modelo.ServTransporte;
import Modelo.SolicitudViaticos;
import Modelo.Tractos;
import Modelo.Umedidas;
import Modelo.Usuarios;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis
 */
public class App_SViaticos extends javax.swing.JInternalFrame {

    /**
     * Creates new form App_SCajaChica
     */
    public static ArrayList<Object[]> lista = new ArrayList<Object[]>();
    public static DefaultTableModel modelo = new DefaultTableModel();
    
    Helper oper;
    HelperUsuarios oU;
    HelperSV oSV;
    HelperConductor oCS;
    HelperRemolque oR;
    HelperST oST;
    HelperTractos oT;
    
    public static int codUM;

    
    public App_SViaticos() {
        initComponents();
        oper = new Helper();
        oU = new HelperUsuarios();
        oSV = new HelperSV();
        oCS = new HelperConductor();
        oR = new HelperRemolque();
        oST = new HelperST();
        oT = new HelperTractos();
        
        String t[]={"COD","CONDUCTOR","TRACTO","REMOLQUE","SERVICIO","SUB-TOTAL"};
        modelo.setColumnIdentifiers(t);
        tablaV.setModel(modelo);
        tablaV.getColumnModel().getColumn(0).setPreferredWidth(1);// 
        tablaV.getColumnModel().getColumn(1).setPreferredWidth(250);
        tablaV.getColumnModel().getColumn(2).setPreferredWidth(35);
        tablaV.getColumnModel().getColumn(3).setPreferredWidth(35);
        tablaV.getColumnModel().getColumn(4).setPreferredWidth(200);
        tablaV.getColumnModel().getColumn(5).setPreferredWidth(50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        imp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaV = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton9 = new javax.swing.JButton();
        desc = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SOLICITUD DE VIATICOS");

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Descripción:");

        imp.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Importe:");

        jButton8.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jButton8.setText("NUEVO");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jButton2.setText("GUARDAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jButton6.setText("SALIR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        tablaV.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(tablaV);

        jButton7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jButton7.setText("-");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jButton9.setText("+");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        desc.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(desc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(imp, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton9))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton8)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        imp.setText("");
        desc.setText("");
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        


        Usuarios u = oU.buscaUsuarios(Integer.parseInt(App_Principal.codigo.getText()));
        SolicitudViaticos temppc = oSV.getLast();
        long corr;
        if(temppc == null){
            corr = 1;
        }else{
            corr = temppc.getSvId() + 1;
        }
        
        String serie = oper.generarSerie(corr,4);
        
        SolicitudViaticos pc = new SolicitudViaticos(u,serie,oper.getF(),desc.getText(),Double.parseDouble(imp.getText()),0,0,0,corr,0);
        oper.registrar(pc);
        

        
        SolicitudViaticos pdc = oSV.buscaSCC(oper.getNextID());

        Iterator<Object[]> itrPartidos = lista.iterator();
        while (itrPartidos.hasNext()) {
            Object[] dv = itrPartidos.next();
            
            Choferes cs = oCS.buscaCd(Integer.parseInt(dv[0].toString()));
            Remolques rq = oR.buscaR(Integer.parseInt(dv[1].toString()));
            ServTransporte stt = oST.buscaST(Integer.parseInt(dv[3].toString()));
            //SV
            Tractos tt = oT.buscaT(Integer.parseInt(dv[2].toString()));
            //dv[4],dv[5],dv[6],dv[7],dv[8],dv[9],dv[10]
            
            DetalleSv dsv = new DetalleSv(cs,rq,stt,pdc,tt,Double.parseDouble(dv[4].toString()),Double.parseDouble(dv[5].toString()),
                    Double.parseDouble(dv[6].toString()),Double.parseDouble(dv[7].toString()),
                    Double.parseDouble(dv[8].toString()),Double.parseDouble(dv[9].toString()),
                    Double.parseDouble(dv[10].toString()));
            
            oper.registrar(dsv);
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mod = (DefaultTableModel)tablaV.getModel(); 
        int fila = tablaV.getSelectedRow();
        mod.removeRow(fila);
        
        
        double total = 0.0;
       for (int i = 0; i <tablaV.getRowCount();  i++) {
            total = total + Double.parseDouble(tablaV.getValueAt(i, 6).toString());
            
        }
       imp.setText(String.valueOf(total));
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        App_DSViaticos eV = new App_DSViaticos();
        App_Principal.escritorio.add(eV);
        eV.setLocation(100, 100);
        eV.show();
    }//GEN-LAST:event_jButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField desc;
    public static javax.swing.JTextField imp;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTable tablaV;
    // End of variables declaration//GEN-END:variables
}
