/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Conn.Conexion;
import Controlador.Helper;
import Controlador.HelperSCC;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Luis
 */
public class App_MisSolicitudesCC extends javax.swing.JInternalFrame {

    /**
     * Creates new form App_MisSolicitudesCC
     */
    HelperSCC oSCC;
    Helper oper;
    DefaultTableModel mod = new DefaultTableModel();
    Conexion conn = new Conexion();
    
    public void updateT(int estado, int codigoU, String busq,int band) {
        oper.limpiaTabla(mod, tablascc);
        if(band == 1)
        {
           mod = oSCC.searchSCC(mod, estado, codigoU); 
        }else{
           mod = oSCC.searchSCCBySerie(mod, codigoU, busq);
        }
        tablascc.setModel(mod);
    }
    
    
    
    
    public App_MisSolicitudesCC() {
        initComponents();
        oSCC = new HelperSCC();
        oper = new Helper();
        String t[]={"ID","SERIE","FECHA","DESCRIPCION","RESPONSABLE","AREA","IMPORTE","MONEDA","ESTADO"};
        mod.setColumnIdentifiers(t);
        if(App_Principal.permisos == 3 || App_Principal.permisos == 2 || App_Principal.permisos == 1){
            mod = oSCC.obtenerSCEXT(mod,App_Principal.permisos,App_Principal.codigoU);
        }else{
            mod = oSCC.obtenerSCC(mod,App_Principal.permisos,App_Principal.codigoU); 
        }
        tablascc.setModel(mod);
        tablascc.getColumnModel().getColumn(0).setPreferredWidth(1);// 
        tablascc.getColumnModel().getColumn(1).setPreferredWidth(90);
        tablascc.getColumnModel().getColumn(2).setPreferredWidth(105);
        tablascc.getColumnModel().getColumn(3).setPreferredWidth(125);
        tablascc.getColumnModel().getColumn(4).setPreferredWidth(125);
        tablascc.getColumnModel().getColumn(5).setPreferredWidth(95);
        tablascc.getColumnModel().getColumn(6).setPreferredWidth(35);
        tablascc.getColumnModel().getColumn(7).setPreferredWidth(35);
        tablascc.getColumnModel().getColumn(8).setPreferredWidth(70);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablascc = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cboSearch = new javax.swing.JComboBox<>();
        buscar = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SOLICITUDES DE CAJA CHICA");

        jScrollPane1.setViewportView(tablascc);

        jButton1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButton1.setText("VER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("BUSCAR:");

        cboSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECCIONAR>", "REGISTRADAS", "APROBADAS", "POR RECABAR DINERO", "CERRADAS", "DENEGADAS" }));

        buscar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jButton3.setText("CARGAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1124, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(buscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (tablascc.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un contrato");
        } else {
            try {
                conn.conectar();

                String dir = "C:\\cajareport\\report_scc.jrxml";
                Map parametros = new HashMap();
                parametros.put("codscc", Integer.parseInt(tablascc.getValueAt(tablascc.getSelectedRow(), 0).toString()));
                JasperReport reporteJasper = JasperCompileManager.compileReport(dir);
                JasperPrint mostrarReporte = JasperFillManager.fillReport(reporteJasper, parametros, conn.getConn());
                JasperViewer.viewReport(mostrarReporte, false);
            } catch (JRException | ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "ERROR: " + ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int estado = cboSearch.getSelectedIndex();
        if(estado  == -1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una opción");
        }else{
           updateT(estado,App_Principal.codigoU,"",1); 
        }
               
    }//GEN-LAST:event_jButton3ActionPerformed

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
        // TODO add your handling code here:
        updateT(0,App_Principal.codigoU,buscar.getText(),2);
        
    }//GEN-LAST:event_buscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscar;
    private javax.swing.JComboBox<String> cboSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablascc;
    // End of variables declaration//GEN-END:variables
}
