package Modelo;
// Generated 08/01/2018 10:56:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cargos generated by hbm2java
 */
public class Cargos  implements java.io.Serializable {


     private Integer cargoId;
     private String cargoDesc;
     private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);

    public Cargos() {
    }

    public Cargos(String cargoDesc) {
        this.cargoDesc = cargoDesc;
    }

    public Cargos(String cargoDesc, Set<Usuarios> usuarioses) {
       this.cargoDesc = cargoDesc;
       this.usuarioses = usuarioses;
    }
   
    public Integer getCargoId() {
        return this.cargoId;
    }
    
    public void setCargoId(Integer cargoId) {
        this.cargoId = cargoId;
    }
    public String getCargoDesc() {
        return this.cargoDesc;
    }
    
    public void setCargoDesc(String cargoDesc) {
        this.cargoDesc = cargoDesc;
    }
    public Set<Usuarios> getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set<Usuarios> usuarioses) {
        this.usuarioses = usuarioses;
    }




}


