package Modelo;
// Generated 08/01/2018 10:56:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Choferes generated by hbm2java
 */
public class Choferes  implements java.io.Serializable {


     private Integer chId;
     private String chNombres;
     private String chDni;
     private String chBrevete;
     private String chTelefono;
     private String chTelefono2;
     private String chSctrcodigo;
     private String chSctrdoc;
     private Integer chEstado;
     private Set<SubMcs> subMcses = new HashSet<SubMcs>(0);
     private Set<DetalleSv> detalleSvs = new HashSet<DetalleSv>(0);

    public Choferes() {
    }

    public Choferes(String chNombres, String chDni, String chBrevete, String chTelefono, String chTelefono2, String chSctrcodigo, String chSctrdoc, Integer chEstado) {
        this.chNombres = chNombres;
        this.chDni = chDni;
        this.chBrevete = chBrevete;
        this.chTelefono = chTelefono;
        this.chTelefono2 = chTelefono2;
        this.chSctrcodigo = chSctrcodigo;
        this.chSctrdoc = chSctrdoc;
        this.chEstado = chEstado;
    }

    public Choferes(String chNombres, String chDni, String chBrevete, String chTelefono, String chTelefono2, String chSctrcodigo, String chSctrdoc, Integer chEstado, Set<SubMcs> subMcses, Set<DetalleSv> detalleSvs) {
       this.chNombres = chNombres;
       this.chDni = chDni;
       this.chBrevete = chBrevete;
       this.chTelefono = chTelefono;
       this.chTelefono2 = chTelefono2;
       this.chSctrcodigo = chSctrcodigo;
       this.chSctrdoc = chSctrdoc;
       this.chEstado = chEstado;
       this.subMcses = subMcses;
       this.detalleSvs = detalleSvs;
    }
   
    public Integer getChId() {
        return this.chId;
    }
    
    public void setChId(Integer chId) {
        this.chId = chId;
    }
    public String getChNombres() {
        return this.chNombres;
    }
    
    public void setChNombres(String chNombres) {
        this.chNombres = chNombres;
    }
    public String getChDni() {
        return this.chDni;
    }
    
    public void setChDni(String chDni) {
        this.chDni = chDni;
    }
    public String getChBrevete() {
        return this.chBrevete;
    }
    
    public void setChBrevete(String chBrevete) {
        this.chBrevete = chBrevete;
    }
    public String getChTelefono() {
        return this.chTelefono;
    }
    
    public void setChTelefono(String chTelefono) {
        this.chTelefono = chTelefono;
    }
    public String getChTelefono2() {
        return this.chTelefono2;
    }
    
    public void setChTelefono2(String chTelefono2) {
        this.chTelefono2 = chTelefono2;
    }
    public String getChSctrcodigo() {
        return this.chSctrcodigo;
    }
    
    public void setChSctrcodigo(String chSctrcodigo) {
        this.chSctrcodigo = chSctrcodigo;
    }
    public String getChSctrdoc() {
        return this.chSctrdoc;
    }
    
    public void setChSctrdoc(String chSctrdoc) {
        this.chSctrdoc = chSctrdoc;
    }
    public Integer getChEstado() {
        return this.chEstado;
    }
    
    public void setChEstado(Integer chEstado) {
        this.chEstado = chEstado;
    }
    public Set<SubMcs> getSubMcses() {
        return this.subMcses;
    }
    
    public void setSubMcses(Set<SubMcs> subMcses) {
        this.subMcses = subMcses;
    }
    public Set<DetalleSv> getDetalleSvs() {
        return this.detalleSvs;
    }
    
    public void setDetalleSvs(Set<DetalleSv> detalleSvs) {
        this.detalleSvs = detalleSvs;
    }




}


