package Modelo;
// Generated 08/01/2018 10:56:44 PM by Hibernate Tools 4.3.1



/**
 * DetalleSc generated by hbm2java
 */
public class DetalleSc  implements java.io.Serializable {


     private Long dscId;
     private SolicitudCaja solicitudCaja;
     private Umedidas umedidas;
     private String dscDesc;
     private String dscUso;
     private Double dscCantidad;
     private Double dscImporte;
     private Double dscSt;

    public DetalleSc() {
    }

    public DetalleSc(SolicitudCaja solicitudCaja, Umedidas umedidas, String dscDesc, String dscUso, Double dscCantidad, Double dscImporte, Double dscSt) {
       this.solicitudCaja = solicitudCaja;
       this.umedidas = umedidas;
       this.dscDesc = dscDesc;
       this.dscUso = dscUso;
       this.dscCantidad = dscCantidad;
       this.dscImporte = dscImporte;
       this.dscSt = dscSt;
    }
   
    public Long getDscId() {
        return this.dscId;
    }
    
    public void setDscId(Long dscId) {
        this.dscId = dscId;
    }
    public SolicitudCaja getSolicitudCaja() {
        return this.solicitudCaja;
    }
    
    public void setSolicitudCaja(SolicitudCaja solicitudCaja) {
        this.solicitudCaja = solicitudCaja;
    }
    public Umedidas getUmedidas() {
        return this.umedidas;
    }
    
    public void setUmedidas(Umedidas umedidas) {
        this.umedidas = umedidas;
    }
    public String getDscDesc() {
        return this.dscDesc;
    }
    
    public void setDscDesc(String dscDesc) {
        this.dscDesc = dscDesc;
    }
    public String getDscUso() {
        return this.dscUso;
    }
    
    public void setDscUso(String dscUso) {
        this.dscUso = dscUso;
    }
    public Double getDscCantidad() {
        return this.dscCantidad;
    }
    
    public void setDscCantidad(Double dscCantidad) {
        this.dscCantidad = dscCantidad;
    }
    public Double getDscImporte() {
        return this.dscImporte;
    }
    
    public void setDscImporte(Double dscImporte) {
        this.dscImporte = dscImporte;
    }
    public Double getDscSt() {
        return this.dscSt;
    }
    
    public void setDscSt(Double dscSt) {
        this.dscSt = dscSt;
    }




}


