package Modelo;
// Generated 08/01/2018 10:56:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * DetalleMcs generated by hbm2java
 */
public class DetalleMcs  implements java.io.Serializable {


     private Long dmcsId;
     private MovimientosCajas movimientosCajas;
     private String unidadmId;
     private String dmcsDesc;
     private Double dmcsCant;
     private Double dmcsImporte;
     private Double dmcsSt;
     private String dmcsDoc;
     private String dmcsProveedor;
     private String dmcsDocserie;
     private Double dmcsDoctotal;
     private Date dmcsDocfecha;
     private Integer dmcsEstado;

    public DetalleMcs() {
    }

    public DetalleMcs(MovimientosCajas movimientosCajas, String unidadmId, String dmcsDesc, Double dmcsCant, Double dmcsImporte, Double dmcsSt, String dmcsDoc, String dmcsProveedor, String dmcsDocserie, Double dmcsDoctotal, Date dmcsDocfecha, Integer dmcsEstado) {
       this.movimientosCajas = movimientosCajas;
       this.unidadmId = unidadmId;
       this.dmcsDesc = dmcsDesc;
       this.dmcsCant = dmcsCant;
       this.dmcsImporte = dmcsImporte;
       this.dmcsSt = dmcsSt;
       this.dmcsDoc = dmcsDoc;
       this.dmcsProveedor = dmcsProveedor;
       this.dmcsDocserie = dmcsDocserie;
       this.dmcsDoctotal = dmcsDoctotal;
       this.dmcsDocfecha = dmcsDocfecha;
       this.dmcsEstado = dmcsEstado;
    }
   
    public Long getDmcsId() {
        return this.dmcsId;
    }
    
    public void setDmcsId(Long dmcsId) {
        this.dmcsId = dmcsId;
    }
    public MovimientosCajas getMovimientosCajas() {
        return this.movimientosCajas;
    }
    
    public void setMovimientosCajas(MovimientosCajas movimientosCajas) {
        this.movimientosCajas = movimientosCajas;
    }
    public String getUnidadmId() {
        return this.unidadmId;
    }
    
    public void setUnidadmId(String unidadmId) {
        this.unidadmId = unidadmId;
    }
    public String getDmcsDesc() {
        return this.dmcsDesc;
    }
    
    public void setDmcsDesc(String dmcsDesc) {
        this.dmcsDesc = dmcsDesc;
    }
    public Double getDmcsCant() {
        return this.dmcsCant;
    }
    
    public void setDmcsCant(Double dmcsCant) {
        this.dmcsCant = dmcsCant;
    }
    public Double getDmcsImporte() {
        return this.dmcsImporte;
    }
    
    public void setDmcsImporte(Double dmcsImporte) {
        this.dmcsImporte = dmcsImporte;
    }
    public Double getDmcsSt() {
        return this.dmcsSt;
    }
    
    public void setDmcsSt(Double dmcsSt) {
        this.dmcsSt = dmcsSt;
    }
    public String getDmcsDoc() {
        return this.dmcsDoc;
    }
    
    public void setDmcsDoc(String dmcsDoc) {
        this.dmcsDoc = dmcsDoc;
    }
    public String getDmcsProveedor() {
        return this.dmcsProveedor;
    }
    
    public void setDmcsProveedor(String dmcsProveedor) {
        this.dmcsProveedor = dmcsProveedor;
    }
    public String getDmcsDocserie() {
        return this.dmcsDocserie;
    }
    
    public void setDmcsDocserie(String dmcsDocserie) {
        this.dmcsDocserie = dmcsDocserie;
    }
    public Double getDmcsDoctotal() {
        return this.dmcsDoctotal;
    }
    
    public void setDmcsDoctotal(Double dmcsDoctotal) {
        this.dmcsDoctotal = dmcsDoctotal;
    }
    public Date getDmcsDocfecha() {
        return this.dmcsDocfecha;
    }
    
    public void setDmcsDocfecha(Date dmcsDocfecha) {
        this.dmcsDocfecha = dmcsDocfecha;
    }
    public Integer getDmcsEstado() {
        return this.dmcsEstado;
    }
    
    public void setDmcsEstado(Integer dmcsEstado) {
        this.dmcsEstado = dmcsEstado;
    }




}


