package Modelo;
// Generated 08/01/2018 10:56:44 PM by Hibernate Tools 4.3.1



/**
 * DetalleSv generated by hbm2java
 */
public class DetalleSv  implements java.io.Serializable {


     private Long dsvId;
     private Choferes choferes;
     private Remolques remolques;
     private ServTransporte servTransporte;
     private SolicitudViaticos solicitudViaticos;
     private Tractos tractos;
     private Double dsvViaticos;
     private Double dsvHospedaje;
     private Double dsvEncarpe;
     private Double dsvDesencarpe;
     private Double dsvVigilancia;
     private Double dsvPropina;
     private Double dsvSt;

    public DetalleSv() {
    }

    public DetalleSv(Choferes choferes, Remolques remolques, ServTransporte servTransporte, SolicitudViaticos solicitudViaticos, Tractos tractos, Double dsvViaticos, Double dsvHospedaje, Double dsvEncarpe, Double dsvDesencarpe, Double dsvVigilancia, Double dsvPropina, Double dsvSt) {
       this.choferes = choferes;
       this.remolques = remolques;
       this.servTransporte = servTransporte;
       this.solicitudViaticos = solicitudViaticos;
       this.tractos = tractos;
       this.dsvViaticos = dsvViaticos;
       this.dsvHospedaje = dsvHospedaje;
       this.dsvEncarpe = dsvEncarpe;
       this.dsvDesencarpe = dsvDesencarpe;
       this.dsvVigilancia = dsvVigilancia;
       this.dsvPropina = dsvPropina;
       this.dsvSt = dsvSt;
    }
   
    public Long getDsvId() {
        return this.dsvId;
    }
    
    public void setDsvId(Long dsvId) {
        this.dsvId = dsvId;
    }
    public Choferes getChoferes() {
        return this.choferes;
    }
    
    public void setChoferes(Choferes choferes) {
        this.choferes = choferes;
    }
    public Remolques getRemolques() {
        return this.remolques;
    }
    
    public void setRemolques(Remolques remolques) {
        this.remolques = remolques;
    }
    public ServTransporte getServTransporte() {
        return this.servTransporte;
    }
    
    public void setServTransporte(ServTransporte servTransporte) {
        this.servTransporte = servTransporte;
    }
    public SolicitudViaticos getSolicitudViaticos() {
        return this.solicitudViaticos;
    }
    
    public void setSolicitudViaticos(SolicitudViaticos solicitudViaticos) {
        this.solicitudViaticos = solicitudViaticos;
    }
    public Tractos getTractos() {
        return this.tractos;
    }
    
    public void setTractos(Tractos tractos) {
        this.tractos = tractos;
    }
    public Double getDsvViaticos() {
        return this.dsvViaticos;
    }
    
    public void setDsvViaticos(Double dsvViaticos) {
        this.dsvViaticos = dsvViaticos;
    }
    public Double getDsvHospedaje() {
        return this.dsvHospedaje;
    }
    
    public void setDsvHospedaje(Double dsvHospedaje) {
        this.dsvHospedaje = dsvHospedaje;
    }
    public Double getDsvEncarpe() {
        return this.dsvEncarpe;
    }
    
    public void setDsvEncarpe(Double dsvEncarpe) {
        this.dsvEncarpe = dsvEncarpe;
    }
    public Double getDsvDesencarpe() {
        return this.dsvDesencarpe;
    }
    
    public void setDsvDesencarpe(Double dsvDesencarpe) {
        this.dsvDesencarpe = dsvDesencarpe;
    }
    public Double getDsvVigilancia() {
        return this.dsvVigilancia;
    }
    
    public void setDsvVigilancia(Double dsvVigilancia) {
        this.dsvVigilancia = dsvVigilancia;
    }
    public Double getDsvPropina() {
        return this.dsvPropina;
    }
    
    public void setDsvPropina(Double dsvPropina) {
        this.dsvPropina = dsvPropina;
    }
    public Double getDsvSt() {
        return this.dsvSt;
    }
    
    public void setDsvSt(Double dsvSt) {
        this.dsvSt = dsvSt;
    }




}


