package Modelo;
// Generated 08/01/2018 10:56:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MovimientosCajas generated by hbm2java
 */
public class MovimientosCajas  implements java.io.Serializable {


     private Long mcsId;
     private Usuarios usuarios;
     private String mcsSerie;
     private Date mcsFecha;
     private String mcsDesc;
     private Double mcsImporte;
     private Double mcsImportel;
     private Double mcsDevolucion;
     private Double mcsReintegro;
     private Integer mcsUsersol;
     private Integer mcsEstado;
     private Long mcsCorrelativo;
     private Integer mcsInout;
     private Set<DetalleMcs> detalleMcses = new HashSet<DetalleMcs>(0);
     private Set<SubMcs> subMcses = new HashSet<SubMcs>(0);
     private Set<SaldoCajas> saldoCajases = new HashSet<SaldoCajas>(0);

    public MovimientosCajas() {
    }

    public MovimientosCajas(Usuarios usuarios, String mcsSerie, Date mcsFecha, String mcsDesc, Double mcsImporte, Double mcsImportel, Double mcsDevolucion, Double mcsReintegro, Integer mcsUsersol, Integer mcsEstado, Long mcsCorrelativo, Integer mcsInout) {
        this.usuarios = usuarios;
        this.mcsSerie = mcsSerie;
        this.mcsFecha = mcsFecha;
        this.mcsDesc = mcsDesc;
        this.mcsImporte = mcsImporte;
        this.mcsImportel = mcsImportel;
        this.mcsDevolucion = mcsDevolucion;
        this.mcsReintegro = mcsReintegro;
        this.mcsUsersol = mcsUsersol;
        this.mcsEstado = mcsEstado;
        this.mcsCorrelativo = mcsCorrelativo;
        this.mcsInout = mcsInout;
    }

    public MovimientosCajas(Usuarios usuarios, String mcsSerie, Date mcsFecha, String mcsDesc, Double mcsImporte, Double mcsImportel, Double mcsDevolucion, Double mcsReintegro, Integer mcsUsersol, Integer mcsEstado, Long mcsCorrelativo, Integer mcsInout, Set<DetalleMcs> detalleMcses, Set<SubMcs> subMcses, Set<SaldoCajas> saldoCajases) {
       this.usuarios = usuarios;
       this.mcsSerie = mcsSerie;
       this.mcsFecha = mcsFecha;
       this.mcsDesc = mcsDesc;
       this.mcsImporte = mcsImporte;
       this.mcsImportel = mcsImportel;
       this.mcsDevolucion = mcsDevolucion;
       this.mcsReintegro = mcsReintegro;
       this.mcsUsersol = mcsUsersol;
       this.mcsEstado = mcsEstado;
       this.mcsCorrelativo = mcsCorrelativo;
       this.mcsInout = mcsInout;
       this.detalleMcses = detalleMcses;
       this.subMcses = subMcses;
       this.saldoCajases = saldoCajases;
    }
   
    public Long getMcsId() {
        return this.mcsId;
    }
    
    public void setMcsId(Long mcsId) {
        this.mcsId = mcsId;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getMcsSerie() {
        return this.mcsSerie;
    }
    
    public void setMcsSerie(String mcsSerie) {
        this.mcsSerie = mcsSerie;
    }
    public Date getMcsFecha() {
        return this.mcsFecha;
    }
    
    public void setMcsFecha(Date mcsFecha) {
        this.mcsFecha = mcsFecha;
    }
    public String getMcsDesc() {
        return this.mcsDesc;
    }
    
    public void setMcsDesc(String mcsDesc) {
        this.mcsDesc = mcsDesc;
    }
    public Double getMcsImporte() {
        return this.mcsImporte;
    }
    
    public void setMcsImporte(Double mcsImporte) {
        this.mcsImporte = mcsImporte;
    }
    public Double getMcsImportel() {
        return this.mcsImportel;
    }
    
    public void setMcsImportel(Double mcsImportel) {
        this.mcsImportel = mcsImportel;
    }
    public Double getMcsDevolucion() {
        return this.mcsDevolucion;
    }
    
    public void setMcsDevolucion(Double mcsDevolucion) {
        this.mcsDevolucion = mcsDevolucion;
    }
    public Double getMcsReintegro() {
        return this.mcsReintegro;
    }
    
    public void setMcsReintegro(Double mcsReintegro) {
        this.mcsReintegro = mcsReintegro;
    }
    public Integer getMcsUsersol() {
        return this.mcsUsersol;
    }
    
    public void setMcsUsersol(Integer mcsUsersol) {
        this.mcsUsersol = mcsUsersol;
    }
    public Integer getMcsEstado() {
        return this.mcsEstado;
    }
    
    public void setMcsEstado(Integer mcsEstado) {
        this.mcsEstado = mcsEstado;
    }
    public Long getMcsCorrelativo() {
        return this.mcsCorrelativo;
    }
    
    public void setMcsCorrelativo(Long mcsCorrelativo) {
        this.mcsCorrelativo = mcsCorrelativo;
    }
    public Integer getMcsInout() {
        return this.mcsInout;
    }
    
    public void setMcsInout(Integer mcsInout) {
        this.mcsInout = mcsInout;
    }
    public Set<DetalleMcs> getDetalleMcses() {
        return this.detalleMcses;
    }
    
    public void setDetalleMcses(Set<DetalleMcs> detalleMcses) {
        this.detalleMcses = detalleMcses;
    }
    public Set<SubMcs> getSubMcses() {
        return this.subMcses;
    }
    
    public void setSubMcses(Set<SubMcs> subMcses) {
        this.subMcses = subMcses;
    }
    public Set<SaldoCajas> getSaldoCajases() {
        return this.saldoCajases;
    }
    
    public void setSaldoCajases(Set<SaldoCajas> saldoCajases) {
        this.saldoCajases = saldoCajases;
    }




}


