package Modelo;
// Generated 08/01/2018 10:56:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MovimientosCajasd generated by hbm2java
 */
public class MovimientosCajasd  implements java.io.Serializable {


     private Long mcdId;
     private Usuarios usuarios;
     private String mcdSerie;
     private Date mcdFecha;
     private String mcdDesc;
     private Double mcdImporte;
     private Double mcdImportel;
     private Double mcdDevolucion;
     private Double mcdReintegro;
     private Integer mcdUsersol;
     private Integer mcdEstado;
     private Long mcdCorrelativo;
     private Integer mcdInout;
     private Set<SaldoCajad> saldoCajads = new HashSet<SaldoCajad>(0);
     private Set<DetalleMcd> detalleMcds = new HashSet<DetalleMcd>(0);

    public MovimientosCajasd() {
    }

    public MovimientosCajasd(Usuarios usuarios, String mcdSerie, Date mcdFecha, String mcdDesc, Double mcdImporte, Double mcdImportel, Double mcdDevolucion, Double mcdReintegro, Integer mcdUsersol, Integer mcdEstado, Long mcdCorrelativo, Integer mcdInout) {
        this.usuarios = usuarios;
        this.mcdSerie = mcdSerie;
        this.mcdFecha = mcdFecha;
        this.mcdDesc = mcdDesc;
        this.mcdImporte = mcdImporte;
        this.mcdImportel = mcdImportel;
        this.mcdDevolucion = mcdDevolucion;
        this.mcdReintegro = mcdReintegro;
        this.mcdUsersol = mcdUsersol;
        this.mcdEstado = mcdEstado;
        this.mcdCorrelativo = mcdCorrelativo;
        this.mcdInout = mcdInout;
    }

    public MovimientosCajasd(Usuarios usuarios, String mcdSerie, Date mcdFecha, String mcdDesc, Double mcdImporte, Double mcdImportel, Double mcdDevolucion, Double mcdReintegro, Integer mcdUsersol, Integer mcdEstado, Long mcdCorrelativo, Integer mcdInout, Set<SaldoCajad> saldoCajads, Set<DetalleMcd> detalleMcds) {
       this.usuarios = usuarios;
       this.mcdSerie = mcdSerie;
       this.mcdFecha = mcdFecha;
       this.mcdDesc = mcdDesc;
       this.mcdImporte = mcdImporte;
       this.mcdImportel = mcdImportel;
       this.mcdDevolucion = mcdDevolucion;
       this.mcdReintegro = mcdReintegro;
       this.mcdUsersol = mcdUsersol;
       this.mcdEstado = mcdEstado;
       this.mcdCorrelativo = mcdCorrelativo;
       this.mcdInout = mcdInout;
       this.saldoCajads = saldoCajads;
       this.detalleMcds = detalleMcds;
    }
   
    public Long getMcdId() {
        return this.mcdId;
    }
    
    public void setMcdId(Long mcdId) {
        this.mcdId = mcdId;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getMcdSerie() {
        return this.mcdSerie;
    }
    
    public void setMcdSerie(String mcdSerie) {
        this.mcdSerie = mcdSerie;
    }
    public Date getMcdFecha() {
        return this.mcdFecha;
    }
    
    public void setMcdFecha(Date mcdFecha) {
        this.mcdFecha = mcdFecha;
    }
    public String getMcdDesc() {
        return this.mcdDesc;
    }
    
    public void setMcdDesc(String mcdDesc) {
        this.mcdDesc = mcdDesc;
    }
    public Double getMcdImporte() {
        return this.mcdImporte;
    }
    
    public void setMcdImporte(Double mcdImporte) {
        this.mcdImporte = mcdImporte;
    }
    public Double getMcdImportel() {
        return this.mcdImportel;
    }
    
    public void setMcdImportel(Double mcdImportel) {
        this.mcdImportel = mcdImportel;
    }
    public Double getMcdDevolucion() {
        return this.mcdDevolucion;
    }
    
    public void setMcdDevolucion(Double mcdDevolucion) {
        this.mcdDevolucion = mcdDevolucion;
    }
    public Double getMcdReintegro() {
        return this.mcdReintegro;
    }
    
    public void setMcdReintegro(Double mcdReintegro) {
        this.mcdReintegro = mcdReintegro;
    }
    public Integer getMcdUsersol() {
        return this.mcdUsersol;
    }
    
    public void setMcdUsersol(Integer mcdUsersol) {
        this.mcdUsersol = mcdUsersol;
    }
    public Integer getMcdEstado() {
        return this.mcdEstado;
    }
    
    public void setMcdEstado(Integer mcdEstado) {
        this.mcdEstado = mcdEstado;
    }
    public Long getMcdCorrelativo() {
        return this.mcdCorrelativo;
    }
    
    public void setMcdCorrelativo(Long mcdCorrelativo) {
        this.mcdCorrelativo = mcdCorrelativo;
    }
    public Integer getMcdInout() {
        return this.mcdInout;
    }
    
    public void setMcdInout(Integer mcdInout) {
        this.mcdInout = mcdInout;
    }
    public Set<SaldoCajad> getSaldoCajads() {
        return this.saldoCajads;
    }
    
    public void setSaldoCajads(Set<SaldoCajad> saldoCajads) {
        this.saldoCajads = saldoCajads;
    }
    public Set<DetalleMcd> getDetalleMcds() {
        return this.detalleMcds;
    }
    
    public void setDetalleMcds(Set<DetalleMcd> detalleMcds) {
        this.detalleMcds = detalleMcds;
    }




}


