package Modelo;
// Generated 08/01/2018 10:56:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Remolques generated by hbm2java
 */
public class Remolques  implements java.io.Serializable {


     private Integer RId;
     private TipoRemolque tipoRemolque;
     private String RPlaca;
     private Double RPesoutil;
     private Date RAfab;
     private String RModelo;
     private String RRegmtc;
     private Integer REstado;
     private Set<SubMcs> subMcses = new HashSet<SubMcs>(0);
     private Set<DetalleSv> detalleSvs = new HashSet<DetalleSv>(0);

    public Remolques() {
    }

    public Remolques(TipoRemolque tipoRemolque, String RPlaca, Double RPesoutil, Date RAfab, String RModelo, String RRegmtc, Integer REstado) {
        this.tipoRemolque = tipoRemolque;
        this.RPlaca = RPlaca;
        this.RPesoutil = RPesoutil;
        this.RAfab = RAfab;
        this.RModelo = RModelo;
        this.RRegmtc = RRegmtc;
        this.REstado = REstado;
    }

    public Remolques(TipoRemolque tipoRemolque, String RPlaca, Double RPesoutil, Date RAfab, String RModelo, String RRegmtc, Integer REstado, Set<SubMcs> subMcses, Set<DetalleSv> detalleSvs) {
       this.tipoRemolque = tipoRemolque;
       this.RPlaca = RPlaca;
       this.RPesoutil = RPesoutil;
       this.RAfab = RAfab;
       this.RModelo = RModelo;
       this.RRegmtc = RRegmtc;
       this.REstado = REstado;
       this.subMcses = subMcses;
       this.detalleSvs = detalleSvs;
    }
   
    public Integer getRId() {
        return this.RId;
    }
    
    public void setRId(Integer RId) {
        this.RId = RId;
    }
    public TipoRemolque getTipoRemolque() {
        return this.tipoRemolque;
    }
    
    public void setTipoRemolque(TipoRemolque tipoRemolque) {
        this.tipoRemolque = tipoRemolque;
    }
    public String getRPlaca() {
        return this.RPlaca;
    }
    
    public void setRPlaca(String RPlaca) {
        this.RPlaca = RPlaca;
    }
    public Double getRPesoutil() {
        return this.RPesoutil;
    }
    
    public void setRPesoutil(Double RPesoutil) {
        this.RPesoutil = RPesoutil;
    }
    public Date getRAfab() {
        return this.RAfab;
    }
    
    public void setRAfab(Date RAfab) {
        this.RAfab = RAfab;
    }
    public String getRModelo() {
        return this.RModelo;
    }
    
    public void setRModelo(String RModelo) {
        this.RModelo = RModelo;
    }
    public String getRRegmtc() {
        return this.RRegmtc;
    }
    
    public void setRRegmtc(String RRegmtc) {
        this.RRegmtc = RRegmtc;
    }
    public Integer getREstado() {
        return this.REstado;
    }
    
    public void setREstado(Integer REstado) {
        this.REstado = REstado;
    }
    public Set<SubMcs> getSubMcses() {
        return this.subMcses;
    }
    
    public void setSubMcses(Set<SubMcs> subMcses) {
        this.subMcses = subMcses;
    }
    public Set<DetalleSv> getDetalleSvs() {
        return this.detalleSvs;
    }
    
    public void setDetalleSvs(Set<DetalleSv> detalleSvs) {
        this.detalleSvs = detalleSvs;
    }




}


