package Modelo;
// Generated 08/01/2018 10:56:44 PM by Hibernate Tools 4.3.1



/**
 * SaldoCajad generated by hbm2java
 */
public class SaldoCajad  implements java.io.Serializable {


     private Long scdId;
     private MovimientosCajasd movimientosCajasd;
     private Double scdDebe;
     private Double scdHaber;
     private Double scdSaldo;
     private Integer scdEstado;

    public SaldoCajad() {
    }

    public SaldoCajad(MovimientosCajasd movimientosCajasd, Double scdDebe, Double scdHaber, Double scdSaldo, Integer scdEstado) {
       this.movimientosCajasd = movimientosCajasd;
       this.scdDebe = scdDebe;
       this.scdHaber = scdHaber;
       this.scdSaldo = scdSaldo;
       this.scdEstado = scdEstado;
    }
   
    public Long getScdId() {
        return this.scdId;
    }
    
    public void setScdId(Long scdId) {
        this.scdId = scdId;
    }
    public MovimientosCajasd getMovimientosCajasd() {
        return this.movimientosCajasd;
    }
    
    public void setMovimientosCajasd(MovimientosCajasd movimientosCajasd) {
        this.movimientosCajasd = movimientosCajasd;
    }
    public Double getScdDebe() {
        return this.scdDebe;
    }
    
    public void setScdDebe(Double scdDebe) {
        this.scdDebe = scdDebe;
    }
    public Double getScdHaber() {
        return this.scdHaber;
    }
    
    public void setScdHaber(Double scdHaber) {
        this.scdHaber = scdHaber;
    }
    public Double getScdSaldo() {
        return this.scdSaldo;
    }
    
    public void setScdSaldo(Double scdSaldo) {
        this.scdSaldo = scdSaldo;
    }
    public Integer getScdEstado() {
        return this.scdEstado;
    }
    
    public void setScdEstado(Integer scdEstado) {
        this.scdEstado = scdEstado;
    }




}


