package Modelo;
// Generated 08/01/2018 10:56:44 PM by Hibernate Tools 4.3.1



/**
 * SaldoCajas generated by hbm2java
 */
public class SaldoCajas  implements java.io.Serializable {


     private Long scsId;
     private MovimientosCajas movimientosCajas;
     private Double scsDebe;
     private Double scsHaber;
     private Double scsSaldo;
     private Integer scsEstado;

    public SaldoCajas() {
    }

    public SaldoCajas(MovimientosCajas movimientosCajas, Double scsDebe, Double scsHaber, Double scsSaldo, Integer scsEstado) {
       this.movimientosCajas = movimientosCajas;
       this.scsDebe = scsDebe;
       this.scsHaber = scsHaber;
       this.scsSaldo = scsSaldo;
       this.scsEstado = scsEstado;
    }
   
    public Long getScsId() {
        return this.scsId;
    }
    
    public void setScsId(Long scsId) {
        this.scsId = scsId;
    }
    public MovimientosCajas getMovimientosCajas() {
        return this.movimientosCajas;
    }
    
    public void setMovimientosCajas(MovimientosCajas movimientosCajas) {
        this.movimientosCajas = movimientosCajas;
    }
    public Double getScsDebe() {
        return this.scsDebe;
    }
    
    public void setScsDebe(Double scsDebe) {
        this.scsDebe = scsDebe;
    }
    public Double getScsHaber() {
        return this.scsHaber;
    }
    
    public void setScsHaber(Double scsHaber) {
        this.scsHaber = scsHaber;
    }
    public Double getScsSaldo() {
        return this.scsSaldo;
    }
    
    public void setScsSaldo(Double scsSaldo) {
        this.scsSaldo = scsSaldo;
    }
    public Integer getScsEstado() {
        return this.scsEstado;
    }
    
    public void setScsEstado(Integer scsEstado) {
        this.scsEstado = scsEstado;
    }




}


