package Modelo;
// Generated 08/01/2018 10:56:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SmDesc generated by hbm2java
 */
public class SmDesc  implements java.io.Serializable {


     private Long deId;
     private SubMcs subMcs;
     private String deDesc;
     private Double deImporte;
     private Date deDocfecha;
     private String deDocserie;
     private String deProveedor;
     private String deDoc;
     private Integer deEstado;

    public SmDesc() {
    }

    public SmDesc(SubMcs subMcs, String deDesc, Double deImporte, Date deDocfecha, String deDocserie, String deProveedor, String deDoc, Integer deEstado) {
       this.subMcs = subMcs;
       this.deDesc = deDesc;
       this.deImporte = deImporte;
       this.deDocfecha = deDocfecha;
       this.deDocserie = deDocserie;
       this.deProveedor = deProveedor;
       this.deDoc = deDoc;
       this.deEstado = deEstado;
    }
   
    public Long getDeId() {
        return this.deId;
    }
    
    public void setDeId(Long deId) {
        this.deId = deId;
    }
    public SubMcs getSubMcs() {
        return this.subMcs;
    }
    
    public void setSubMcs(SubMcs subMcs) {
        this.subMcs = subMcs;
    }
    public String getDeDesc() {
        return this.deDesc;
    }
    
    public void setDeDesc(String deDesc) {
        this.deDesc = deDesc;
    }
    public Double getDeImporte() {
        return this.deImporte;
    }
    
    public void setDeImporte(Double deImporte) {
        this.deImporte = deImporte;
    }
    public Date getDeDocfecha() {
        return this.deDocfecha;
    }
    
    public void setDeDocfecha(Date deDocfecha) {
        this.deDocfecha = deDocfecha;
    }
    public String getDeDocserie() {
        return this.deDocserie;
    }
    
    public void setDeDocserie(String deDocserie) {
        this.deDocserie = deDocserie;
    }
    public String getDeProveedor() {
        return this.deProveedor;
    }
    
    public void setDeProveedor(String deProveedor) {
        this.deProveedor = deProveedor;
    }
    public String getDeDoc() {
        return this.deDoc;
    }
    
    public void setDeDoc(String deDoc) {
        this.deDoc = deDoc;
    }
    public Integer getDeEstado() {
        return this.deEstado;
    }
    
    public void setDeEstado(Integer deEstado) {
        this.deEstado = deEstado;
    }




}


