package Modelo;
// Generated 08/01/2018 10:56:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SmEnc generated by hbm2java
 */
public class SmEnc  implements java.io.Serializable {


     private Long EId;
     private SubMcs subMcs;
     private String EDesc;
     private Double EImporte;
     private Date EDocfecha;
     private String EDocserie;
     private String EProveedor;
     private String EDoc;
     private Integer EEstado;

    public SmEnc() {
    }

    public SmEnc(SubMcs subMcs, String EDesc, Double EImporte, Date EDocfecha, String EDocserie, String EProveedor, String EDoc, Integer EEstado) {
       this.subMcs = subMcs;
       this.EDesc = EDesc;
       this.EImporte = EImporte;
       this.EDocfecha = EDocfecha;
       this.EDocserie = EDocserie;
       this.EProveedor = EProveedor;
       this.EDoc = EDoc;
       this.EEstado = EEstado;
    }
   
    public Long getEId() {
        return this.EId;
    }
    
    public void setEId(Long EId) {
        this.EId = EId;
    }
    public SubMcs getSubMcs() {
        return this.subMcs;
    }
    
    public void setSubMcs(SubMcs subMcs) {
        this.subMcs = subMcs;
    }
    public String getEDesc() {
        return this.EDesc;
    }
    
    public void setEDesc(String EDesc) {
        this.EDesc = EDesc;
    }
    public Double getEImporte() {
        return this.EImporte;
    }
    
    public void setEImporte(Double EImporte) {
        this.EImporte = EImporte;
    }
    public Date getEDocfecha() {
        return this.EDocfecha;
    }
    
    public void setEDocfecha(Date EDocfecha) {
        this.EDocfecha = EDocfecha;
    }
    public String getEDocserie() {
        return this.EDocserie;
    }
    
    public void setEDocserie(String EDocserie) {
        this.EDocserie = EDocserie;
    }
    public String getEProveedor() {
        return this.EProveedor;
    }
    
    public void setEProveedor(String EProveedor) {
        this.EProveedor = EProveedor;
    }
    public String getEDoc() {
        return this.EDoc;
    }
    
    public void setEDoc(String EDoc) {
        this.EDoc = EDoc;
    }
    public Integer getEEstado() {
        return this.EEstado;
    }
    
    public void setEEstado(Integer EEstado) {
        this.EEstado = EEstado;
    }




}


