package Modelo;
// Generated 08/01/2018 10:56:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SmHospedaje generated by hbm2java
 */
public class SmHospedaje  implements java.io.Serializable {


     private Long HId;
     private SubMcs subMcs;
     private String HDesc;
     private Double HImporte;
     private Date HDocfecha;
     private String HDocserie;
     private String HProveedor;
     private String HDoc;
     private Integer HEstado;

    public SmHospedaje() {
    }

    public SmHospedaje(SubMcs subMcs, String HDesc, Double HImporte, Date HDocfecha, String HDocserie, String HProveedor, String HDoc, Integer HEstado) {
       this.subMcs = subMcs;
       this.HDesc = HDesc;
       this.HImporte = HImporte;
       this.HDocfecha = HDocfecha;
       this.HDocserie = HDocserie;
       this.HProveedor = HProveedor;
       this.HDoc = HDoc;
       this.HEstado = HEstado;
    }
   
    public Long getHId() {
        return this.HId;
    }
    
    public void setHId(Long HId) {
        this.HId = HId;
    }
    public SubMcs getSubMcs() {
        return this.subMcs;
    }
    
    public void setSubMcs(SubMcs subMcs) {
        this.subMcs = subMcs;
    }
    public String getHDesc() {
        return this.HDesc;
    }
    
    public void setHDesc(String HDesc) {
        this.HDesc = HDesc;
    }
    public Double getHImporte() {
        return this.HImporte;
    }
    
    public void setHImporte(Double HImporte) {
        this.HImporte = HImporte;
    }
    public Date getHDocfecha() {
        return this.HDocfecha;
    }
    
    public void setHDocfecha(Date HDocfecha) {
        this.HDocfecha = HDocfecha;
    }
    public String getHDocserie() {
        return this.HDocserie;
    }
    
    public void setHDocserie(String HDocserie) {
        this.HDocserie = HDocserie;
    }
    public String getHProveedor() {
        return this.HProveedor;
    }
    
    public void setHProveedor(String HProveedor) {
        this.HProveedor = HProveedor;
    }
    public String getHDoc() {
        return this.HDoc;
    }
    
    public void setHDoc(String HDoc) {
        this.HDoc = HDoc;
    }
    public Integer getHEstado() {
        return this.HEstado;
    }
    
    public void setHEstado(Integer HEstado) {
        this.HEstado = HEstado;
    }




}


