package Modelo;
// Generated 08/01/2018 10:56:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SmPropina generated by hbm2java
 */
public class SmPropina  implements java.io.Serializable {


     private Long PId;
     private SubMcs subMcs;
     private String PDesc;
     private Double PImporte;
     private Date PDocfecha;
     private String PDocserie;
     private String PProveedor;
     private String PDoc;
     private Integer PEstado;

    public SmPropina() {
    }

    public SmPropina(SubMcs subMcs, String PDesc, Double PImporte, Date PDocfecha, String PDocserie, String PProveedor, String PDoc, Integer PEstado) {
       this.subMcs = subMcs;
       this.PDesc = PDesc;
       this.PImporte = PImporte;
       this.PDocfecha = PDocfecha;
       this.PDocserie = PDocserie;
       this.PProveedor = PProveedor;
       this.PDoc = PDoc;
       this.PEstado = PEstado;
    }
   
    public Long getPId() {
        return this.PId;
    }
    
    public void setPId(Long PId) {
        this.PId = PId;
    }
    public SubMcs getSubMcs() {
        return this.subMcs;
    }
    
    public void setSubMcs(SubMcs subMcs) {
        this.subMcs = subMcs;
    }
    public String getPDesc() {
        return this.PDesc;
    }
    
    public void setPDesc(String PDesc) {
        this.PDesc = PDesc;
    }
    public Double getPImporte() {
        return this.PImporte;
    }
    
    public void setPImporte(Double PImporte) {
        this.PImporte = PImporte;
    }
    public Date getPDocfecha() {
        return this.PDocfecha;
    }
    
    public void setPDocfecha(Date PDocfecha) {
        this.PDocfecha = PDocfecha;
    }
    public String getPDocserie() {
        return this.PDocserie;
    }
    
    public void setPDocserie(String PDocserie) {
        this.PDocserie = PDocserie;
    }
    public String getPProveedor() {
        return this.PProveedor;
    }
    
    public void setPProveedor(String PProveedor) {
        this.PProveedor = PProveedor;
    }
    public String getPDoc() {
        return this.PDoc;
    }
    
    public void setPDoc(String PDoc) {
        this.PDoc = PDoc;
    }
    public Integer getPEstado() {
        return this.PEstado;
    }
    
    public void setPEstado(Integer PEstado) {
        this.PEstado = PEstado;
    }




}


