package Modelo;
// Generated 08/01/2018 10:56:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SmVigilancia generated by hbm2java
 */
public class SmVigilancia  implements java.io.Serializable {


     private Long viId;
     private SubMcs subMcs;
     private String viDesc;
     private Double viImporte;
     private Date viDocfecha;
     private String viDocserie;
     private String viProveedor;
     private String viDoc;
     private Integer viEstado;

    public SmVigilancia() {
    }

    public SmVigilancia(SubMcs subMcs, String viDesc, Double viImporte, Date viDocfecha, String viDocserie, String viProveedor, String viDoc, Integer viEstado) {
       this.subMcs = subMcs;
       this.viDesc = viDesc;
       this.viImporte = viImporte;
       this.viDocfecha = viDocfecha;
       this.viDocserie = viDocserie;
       this.viProveedor = viProveedor;
       this.viDoc = viDoc;
       this.viEstado = viEstado;
    }
   
    public Long getViId() {
        return this.viId;
    }
    
    public void setViId(Long viId) {
        this.viId = viId;
    }
    public SubMcs getSubMcs() {
        return this.subMcs;
    }
    
    public void setSubMcs(SubMcs subMcs) {
        this.subMcs = subMcs;
    }
    public String getViDesc() {
        return this.viDesc;
    }
    
    public void setViDesc(String viDesc) {
        this.viDesc = viDesc;
    }
    public Double getViImporte() {
        return this.viImporte;
    }
    
    public void setViImporte(Double viImporte) {
        this.viImporte = viImporte;
    }
    public Date getViDocfecha() {
        return this.viDocfecha;
    }
    
    public void setViDocfecha(Date viDocfecha) {
        this.viDocfecha = viDocfecha;
    }
    public String getViDocserie() {
        return this.viDocserie;
    }
    
    public void setViDocserie(String viDocserie) {
        this.viDocserie = viDocserie;
    }
    public String getViProveedor() {
        return this.viProveedor;
    }
    
    public void setViProveedor(String viProveedor) {
        this.viProveedor = viProveedor;
    }
    public String getViDoc() {
        return this.viDoc;
    }
    
    public void setViDoc(String viDoc) {
        this.viDoc = viDoc;
    }
    public Integer getViEstado() {
        return this.viEstado;
    }
    
    public void setViEstado(Integer viEstado) {
        this.viEstado = viEstado;
    }




}


