package Modelo;
// Generated 08/01/2018 10:56:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SmViaticos generated by hbm2java
 */
public class SmViaticos  implements java.io.Serializable {


     private Long VId;
     private SubMcs subMcs;
     private String VDesc;
     private Double VImporte;
     private Date VDocfecha;
     private String VDocserie;
     private String VProveedor;
     private String VDoc;
     private Integer VEstado;

    public SmViaticos() {
    }

    public SmViaticos(SubMcs subMcs, String VDesc, Double VImporte, Date VDocfecha, String VDocserie, String VProveedor, String VDoc, Integer VEstado) {
       this.subMcs = subMcs;
       this.VDesc = VDesc;
       this.VImporte = VImporte;
       this.VDocfecha = VDocfecha;
       this.VDocserie = VDocserie;
       this.VProveedor = VProveedor;
       this.VDoc = VDoc;
       this.VEstado = VEstado;
    }
   
    public Long getVId() {
        return this.VId;
    }
    
    public void setVId(Long VId) {
        this.VId = VId;
    }
    public SubMcs getSubMcs() {
        return this.subMcs;
    }
    
    public void setSubMcs(SubMcs subMcs) {
        this.subMcs = subMcs;
    }
    public String getVDesc() {
        return this.VDesc;
    }
    
    public void setVDesc(String VDesc) {
        this.VDesc = VDesc;
    }
    public Double getVImporte() {
        return this.VImporte;
    }
    
    public void setVImporte(Double VImporte) {
        this.VImporte = VImporte;
    }
    public Date getVDocfecha() {
        return this.VDocfecha;
    }
    
    public void setVDocfecha(Date VDocfecha) {
        this.VDocfecha = VDocfecha;
    }
    public String getVDocserie() {
        return this.VDocserie;
    }
    
    public void setVDocserie(String VDocserie) {
        this.VDocserie = VDocserie;
    }
    public String getVProveedor() {
        return this.VProveedor;
    }
    
    public void setVProveedor(String VProveedor) {
        this.VProveedor = VProveedor;
    }
    public String getVDoc() {
        return this.VDoc;
    }
    
    public void setVDoc(String VDoc) {
        this.VDoc = VDoc;
    }
    public Integer getVEstado() {
        return this.VEstado;
    }
    
    public void setVEstado(Integer VEstado) {
        this.VEstado = VEstado;
    }




}


