package Modelo;
// Generated 08/01/2018 10:56:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SolicitudCaja generated by hbm2java
 */
public class SolicitudCaja  implements java.io.Serializable {


     private Long scId;
     private Usuarios usuarios;
     private String scSerie;
     private Date spFecha;
     private Integer spTm;
     private String scDesc;
     private Double scImporte;
     private Integer scAprob1;
     private Integer scAprob2;
     private Integer scAprob3;
     private Long scCorrelativo;
     private Integer scEstado;
     private Set<DetalleSc> detalleScs = new HashSet<DetalleSc>(0);

    public SolicitudCaja() {
    }

    public SolicitudCaja(Usuarios usuarios, String scSerie, Date spFecha, Integer spTm, String scDesc, Double scImporte, Integer scAprob1, Integer scAprob2, Integer scAprob3, Long scCorrelativo, Integer scEstado) {
        this.usuarios = usuarios;
        this.scSerie = scSerie;
        this.spFecha = spFecha;
        this.spTm = spTm;
        this.scDesc = scDesc;
        this.scImporte = scImporte;
        this.scAprob1 = scAprob1;
        this.scAprob2 = scAprob2;
        this.scAprob3 = scAprob3;
        this.scCorrelativo = scCorrelativo;
        this.scEstado = scEstado;
    }

    public SolicitudCaja(Usuarios usuarios, String scSerie, Date spFecha, Integer spTm, String scDesc, Double scImporte, Integer scAprob1, Integer scAprob2, Integer scAprob3, Long scCorrelativo, Integer scEstado, Set<DetalleSc> detalleScs) {
       this.usuarios = usuarios;
       this.scSerie = scSerie;
       this.spFecha = spFecha;
       this.spTm = spTm;
       this.scDesc = scDesc;
       this.scImporte = scImporte;
       this.scAprob1 = scAprob1;
       this.scAprob2 = scAprob2;
       this.scAprob3 = scAprob3;
       this.scCorrelativo = scCorrelativo;
       this.scEstado = scEstado;
       this.detalleScs = detalleScs;
    }
   
    public Long getScId() {
        return this.scId;
    }
    
    public void setScId(Long scId) {
        this.scId = scId;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getScSerie() {
        return this.scSerie;
    }
    
    public void setScSerie(String scSerie) {
        this.scSerie = scSerie;
    }
    public Date getSpFecha() {
        return this.spFecha;
    }
    
    public void setSpFecha(Date spFecha) {
        this.spFecha = spFecha;
    }
    public Integer getSpTm() {
        return this.spTm;
    }
    
    public void setSpTm(Integer spTm) {
        this.spTm = spTm;
    }
    public String getScDesc() {
        return this.scDesc;
    }
    
    public void setScDesc(String scDesc) {
        this.scDesc = scDesc;
    }
    public Double getScImporte() {
        return this.scImporte;
    }
    
    public void setScImporte(Double scImporte) {
        this.scImporte = scImporte;
    }
    public Integer getScAprob1() {
        return this.scAprob1;
    }
    
    public void setScAprob1(Integer scAprob1) {
        this.scAprob1 = scAprob1;
    }
    public Integer getScAprob2() {
        return this.scAprob2;
    }
    
    public void setScAprob2(Integer scAprob2) {
        this.scAprob2 = scAprob2;
    }
    public Integer getScAprob3() {
        return this.scAprob3;
    }
    
    public void setScAprob3(Integer scAprob3) {
        this.scAprob3 = scAprob3;
    }
    public Long getScCorrelativo() {
        return this.scCorrelativo;
    }
    
    public void setScCorrelativo(Long scCorrelativo) {
        this.scCorrelativo = scCorrelativo;
    }
    public Integer getScEstado() {
        return this.scEstado;
    }
    
    public void setScEstado(Integer scEstado) {
        this.scEstado = scEstado;
    }
    public Set<DetalleSc> getDetalleScs() {
        return this.detalleScs;
    }
    
    public void setDetalleScs(Set<DetalleSc> detalleScs) {
        this.detalleScs = detalleScs;
    }




}


