package Modelo;
// Generated 08/01/2018 10:56:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SolicitudViaticos generated by hbm2java
 */
public class SolicitudViaticos  implements java.io.Serializable {


     private Long svId;
     private Usuarios usuarios;
     private String svSerie;
     private Date svFechas;
     private String svDesc;
     private Double svImporte;
     private Integer svAprob1;
     private Integer spAprob2;
     private Integer spAprob3;
     private Long svCorrelativo;
     private Integer svEstado;
     private Set<DetalleSv> detalleSvs = new HashSet<DetalleSv>(0);

    public SolicitudViaticos() {
    }

    public SolicitudViaticos(Usuarios usuarios, String svSerie, Date svFechas, String svDesc, Double svImporte, Integer svAprob1, Integer spAprob2, Integer spAprob3, Long svCorrelativo, Integer svEstado) {
        this.usuarios = usuarios;
        this.svSerie = svSerie;
        this.svFechas = svFechas;
        this.svDesc = svDesc;
        this.svImporte = svImporte;
        this.svAprob1 = svAprob1;
        this.spAprob2 = spAprob2;
        this.spAprob3 = spAprob3;
        this.svCorrelativo = svCorrelativo;
        this.svEstado = svEstado;
    }

    public SolicitudViaticos(Usuarios usuarios, String svSerie, Date svFechas, String svDesc, Double svImporte, Integer svAprob1, Integer spAprob2, Integer spAprob3, Long svCorrelativo, Integer svEstado, Set<DetalleSv> detalleSvs) {
       this.usuarios = usuarios;
       this.svSerie = svSerie;
       this.svFechas = svFechas;
       this.svDesc = svDesc;
       this.svImporte = svImporte;
       this.svAprob1 = svAprob1;
       this.spAprob2 = spAprob2;
       this.spAprob3 = spAprob3;
       this.svCorrelativo = svCorrelativo;
       this.svEstado = svEstado;
       this.detalleSvs = detalleSvs;
    }
   
    public Long getSvId() {
        return this.svId;
    }
    
    public void setSvId(Long svId) {
        this.svId = svId;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getSvSerie() {
        return this.svSerie;
    }
    
    public void setSvSerie(String svSerie) {
        this.svSerie = svSerie;
    }
    public Date getSvFechas() {
        return this.svFechas;
    }
    
    public void setSvFechas(Date svFechas) {
        this.svFechas = svFechas;
    }
    public String getSvDesc() {
        return this.svDesc;
    }
    
    public void setSvDesc(String svDesc) {
        this.svDesc = svDesc;
    }
    public Double getSvImporte() {
        return this.svImporte;
    }
    
    public void setSvImporte(Double svImporte) {
        this.svImporte = svImporte;
    }
    public Integer getSvAprob1() {
        return this.svAprob1;
    }
    
    public void setSvAprob1(Integer svAprob1) {
        this.svAprob1 = svAprob1;
    }
    public Integer getSpAprob2() {
        return this.spAprob2;
    }
    
    public void setSpAprob2(Integer spAprob2) {
        this.spAprob2 = spAprob2;
    }
    public Integer getSpAprob3() {
        return this.spAprob3;
    }
    
    public void setSpAprob3(Integer spAprob3) {
        this.spAprob3 = spAprob3;
    }
    public Long getSvCorrelativo() {
        return this.svCorrelativo;
    }
    
    public void setSvCorrelativo(Long svCorrelativo) {
        this.svCorrelativo = svCorrelativo;
    }
    public Integer getSvEstado() {
        return this.svEstado;
    }
    
    public void setSvEstado(Integer svEstado) {
        this.svEstado = svEstado;
    }
    public Set<DetalleSv> getDetalleSvs() {
        return this.detalleSvs;
    }
    
    public void setDetalleSvs(Set<DetalleSv> detalleSvs) {
        this.detalleSvs = detalleSvs;
    }




}


