package Modelo;
// Generated 08/01/2018 10:56:44 PM by Hibernate Tools 4.3.1



/**
 * TipoTservicio generated by hbm2java
 */
public class TipoTservicio  implements java.io.Serializable {


     private Integer tsId;
     private String tsDesc;

    public TipoTservicio() {
    }

    public TipoTservicio(String tsDesc) {
       this.tsDesc = tsDesc;
    }
   
    public Integer getTsId() {
        return this.tsId;
    }
    
    public void setTsId(Integer tsId) {
        this.tsId = tsId;
    }
    public String getTsDesc() {
        return this.tsDesc;
    }
    
    public void setTsDesc(String tsDesc) {
        this.tsDesc = tsDesc;
    }




}


