package Modelo;
// Generated 08/01/2018 10:56:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tractos generated by hbm2java
 */
public class Tractos  implements java.io.Serializable {


     private Integer TId;
     private String TPlaca;
     private String TMarca;
     private String TModelo;
     private String TConfvehi;
     private String TRegmtc;
     private Integer TEstado;
     private Set<DetalleSv> detalleSvs = new HashSet<DetalleSv>(0);
     private Set<SubMcs> subMcses = new HashSet<SubMcs>(0);

    public Tractos() {
    }

    public Tractos(String TPlaca, String TMarca, String TModelo, String TConfvehi, String TRegmtc, Integer TEstado) {
        this.TPlaca = TPlaca;
        this.TMarca = TMarca;
        this.TModelo = TModelo;
        this.TConfvehi = TConfvehi;
        this.TRegmtc = TRegmtc;
        this.TEstado = TEstado;
    }

    public Tractos(String TPlaca, String TMarca, String TModelo, String TConfvehi, String TRegmtc, Integer TEstado, Set<DetalleSv> detalleSvs, Set<SubMcs> subMcses) {
       this.TPlaca = TPlaca;
       this.TMarca = TMarca;
       this.TModelo = TModelo;
       this.TConfvehi = TConfvehi;
       this.TRegmtc = TRegmtc;
       this.TEstado = TEstado;
       this.detalleSvs = detalleSvs;
       this.subMcses = subMcses;
    }
   
    public Integer getTId() {
        return this.TId;
    }
    
    public void setTId(Integer TId) {
        this.TId = TId;
    }
    public String getTPlaca() {
        return this.TPlaca;
    }
    
    public void setTPlaca(String TPlaca) {
        this.TPlaca = TPlaca;
    }
    public String getTMarca() {
        return this.TMarca;
    }
    
    public void setTMarca(String TMarca) {
        this.TMarca = TMarca;
    }
    public String getTModelo() {
        return this.TModelo;
    }
    
    public void setTModelo(String TModelo) {
        this.TModelo = TModelo;
    }
    public String getTConfvehi() {
        return this.TConfvehi;
    }
    
    public void setTConfvehi(String TConfvehi) {
        this.TConfvehi = TConfvehi;
    }
    public String getTRegmtc() {
        return this.TRegmtc;
    }
    
    public void setTRegmtc(String TRegmtc) {
        this.TRegmtc = TRegmtc;
    }
    public Integer getTEstado() {
        return this.TEstado;
    }
    
    public void setTEstado(Integer TEstado) {
        this.TEstado = TEstado;
    }
    public Set<DetalleSv> getDetalleSvs() {
        return this.detalleSvs;
    }
    
    public void setDetalleSvs(Set<DetalleSv> detalleSvs) {
        this.detalleSvs = detalleSvs;
    }
    public Set<SubMcs> getSubMcses() {
        return this.subMcses;
    }
    
    public void setSubMcses(Set<SubMcs> subMcses) {
        this.subMcses = subMcses;
    }




}


